using UnityEngine;

public class HUDHandler : MonoBehaviour
{
    static AudioSource sfx; static Material effectMaterial;
    public float maxX=480,minX=-480,maxY=480,minY=-480,numVirusStart=20,numCellsStart=100,timeStep=8,multiplier=200;
    public int xDir,yDir,minCells;
    public Rigidbody virus,dummyvirus,whiteCell,cell;
    public Transform virusClone,dummyClone,whiteCellClone,cellClone;
    public Texture winScreen,loseScreen,pauseScreen,splashScreen,intro1,controlsScreen;
    public Font newFont;
    public AudioSource death,win,corruption;
    public Material explosionMaterial;
    enum GameState { Splash,Game,Pause,Win,Lose,Intro }
    GameState state=GameState.Splash;
    float startTime,newTime,maxVirus,endElapsed; bool endSound; int introPage,endScore,endLost;
    public static void PlaySfx(AudioClip clip,float volume=1f){if(!clip)return;if(!sfx){var host=new GameObject("Disease Destroyer SFX");DontDestroyOnLoad(host);sfx=host.AddComponent<AudioSource>();sfx.playOnAwake=false;sfx.spatialBlend=0;sfx.volume=1;}sfx.PlayOneShot(clip,volume);}
    public static void Explode(Vector3 position,Color color,float scale=1f){var host=new GameObject("Explosion");host.transform.position=new Vector3(position.x,position.y,-5);var particles=host.AddComponent<ParticleSystem>();var main=particles.main;main.duration=.35f;main.loop=false;main.playOnAwake=false;main.simulationSpace=ParticleSystemSimulationSpace.World;main.startLifetime=new ParticleSystem.MinMaxCurve(.3f,.7f);main.startSpeed=new ParticleSystem.MinMaxCurve(35*scale,95*scale);main.startSize=new ParticleSystem.MinMaxCurve(5*scale,13*scale);main.startColor=new ParticleSystem.MinMaxGradient(color,new Color(1,.9f,.45f,1));main.maxParticles=60;var emission=particles.emission;emission.rateOverTime=0;emission.SetBursts(new[]{new ParticleSystem.Burst(0,36)});var shape=particles.shape;shape.shapeType=ParticleSystemShapeType.Sphere;shape.radius=5*scale;var renderer=particles.GetComponent<ParticleSystemRenderer>();renderer.renderMode=ParticleSystemRenderMode.Billboard;if(effectMaterial)renderer.sharedMaterial=effectMaterial;particles.Play();Destroy(host,2);}
    void Start(){AudioListener.volume=.4f;effectMaterial=explosionMaterial;if(effectMaterial)effectMaterial.mainTexture=CreateSoftParticleTexture();numVirusStart=20;numCellsStart=100;SpawnCells();for(var i=0;i<numVirusStart;i++)Instantiate(virus,new Vector3(Random.Range(minX+100,maxX-100),Random.Range(minY+100,maxY-100),0),virus.rotation);maxVirus=numVirusStart;newTime=Time.time+timeStep;}
    Texture2D CreateSoftParticleTexture(){const int size=64;var texture=new Texture2D(size,size,TextureFormat.RGBA32,false){name="Soft Explosion Particle",filterMode=FilterMode.Bilinear,wrapMode=TextureWrapMode.Clamp};var pixels=new Color[size*size];for(var y=0;y<size;y++)for(var x=0;x<size;x++){var dx=(x+.5f)/size*2-1;var dy=(y+.5f)/size*2-1;var distance=Mathf.Sqrt(dx*dx+dy*dy);var alpha=Mathf.SmoothStep(1,0,Mathf.Clamp01(distance));alpha*=alpha;pixels[y*size+x]=new Color(1,1,1,alpha);}texture.SetPixels(pixels);texture.Apply(false,true);return texture;}
    void SpawnCells(){var side=Mathf.RoundToInt(Mathf.Sqrt(numCellsStart));for(var i=0;i<side;i++)for(var j=0;j<side;j++){var rb=Instantiate(cell,new Vector3(i/(float)side*1000-500,j/(float)side*1000-500,0),cell.rotation);rb.constraints|=RigidbodyConstraints.FreezeRotation;rb.linearVelocity=new Vector3(Random.Range(-1f,1f)*1000,Random.Range(-1f,1f)*1000,0);}}
    void Update(){var cells=GameObject.FindGameObjectsWithTag("Respawn");var viruses=GameObject.FindGameObjectsWithTag("Finish");if(Input.GetKeyDown(KeyCode.P)){if(state==GameState.Game)state=GameState.Pause;else if(state==GameState.Pause)state=GameState.Game;}if(state==GameState.Game&&viruses.Length==0)Finish(GameState.Win,cells.Length);else if(state==GameState.Game&&cells.Length<=minCells)Finish(GameState.Lose,cells.Length);
        if(state==GameState.Game){Time.timeScale=1;endSound=false;CorruptCell();}else if(state==GameState.Pause)Time.timeScale=0;else if(state==GameState.Splash){Time.timeScale=0;if(Advance()){introPage=0;state=GameState.Intro;}}else if(state==GameState.Intro){Time.timeScale=0;if(Advance()){if(introPage==0)introPage=1;else{state=GameState.Game;startTime=Time.time;}}}else if(state==GameState.Win){Time.timeScale=0;if(!endSound){if(win)PlaySfx(win.clip,win.volume);endSound=true;}}else if(state==GameState.Lose){Time.timeScale=0;endSound=true;}}
    void Finish(GameState result,int cells){endScore=cells*100;endLost=Mathf.Max(0,Mathf.RoundToInt(numCellsStart)-cells);endElapsed=Mathf.Max(0,Time.time-startTime);state=result;Time.timeScale=0;}
    bool Advance()=>Input.GetMouseButtonDown(0)||Input.GetMouseButtonDown(1)||Input.GetKeyDown(KeyCode.Space);
    void CorruptCell(){if(Time.time<newTime)return;var cells=GameObject.FindGameObjectsWithTag("Respawn");if(cells.Length>0){GameObject farthest=null;float best=-1;foreach(var c in cells){var d=(c.transform.position-transform.position).sqrMagnitude;if(d>best){best=d;farthest=c;}}if(corruption)PlaySfx(corruption.clip,corruption.volume);farthest.GetComponent<cellMovement>()?.corrupt();}newTime=Time.time+timeStep+Random.Range(0,3f);}
    void OnGUI(){const float w=960,h=540;var cells=GameObject.FindGameObjectsWithTag("Respawn");var viruses=GameObject.FindGameObjectsWithTag("Finish");if(state==GameState.Splash){DrawFull(splashScreen,Screen.width,Screen.height);return;}if(state==GameState.Intro){DrawFull(introPage==0?intro1:controlsScreen,Screen.width,Screen.height);return;}if(state==GameState.Pause){DrawFull(pauseScreen,Screen.width,Screen.height);return;}var scale=Mathf.Min(Screen.width/w,Screen.height/h);var offset=new Vector3((Screen.width-w*scale)*.5f,(Screen.height-h*scale)*.5f,0);if(state==GameState.Win||state==GameState.Lose)DrawFull(state==GameState.Win?winScreen:loseScreen,Screen.width,Screen.height);GUI.matrix=Matrix4x4.TRS(offset,Quaternion.identity,new Vector3(scale,scale,1));if(newFont)GUI.skin.font=newFont;if(state==GameState.Win||state==GameState.Lose){GUI.Label(new Rect(w/2-330,h/2+45,300,200),endScore.ToString());GUI.Label(new Rect(w/2-25,h/2+45,300,200),endLost.ToString());GUI.Label(new Rect(w/2+225,h/2+45,300,200),endElapsed.ToString("0.0"));if(Advance())Restart();return;}GUI.Label(new Rect(w/2-310,2,180,40),"SCORE: "+(cells.Length*100));GUI.Label(new Rect(w/4+50,2,240,40),"CELLS REMAINING: "+cells.Length);GUI.Label(new Rect(w/2+30,2,240,40),"VIRUSES REMAINING: "+viruses.Length);var p=GameObject.FindGameObjectWithTag("Player");if(p&&p.GetComponent<playerMovement>().slow)GUI.Label(new Rect(w/2-30,h*.75f,200,40),"SLOWED");}
    void DrawFull(Texture t,float width,float height){if(t)GUI.DrawTexture(new Rect(0,0,width,height),t,ScaleMode.StretchToFill,true);}
    void Restart(){foreach(var o in GameObject.FindGameObjectsWithTag("Respawn"))Destroy(o);foreach(var o in GameObject.FindGameObjectsWithTag("Finish"))Destroy(o);GameObject.FindGameObjectWithTag("Player")?.GetComponent<playerMovement>()?.restart();state=GameState.Game;startTime=Time.time;SpawnCells();for(var i=0;i<numVirusStart;i++)Instantiate(virus,new Vector3(Random.Range(minX+100,maxX-100),Random.Range(minY+100,maxY-100),0),virus.rotation);newTime=Time.time+timeStep;}
}
